export type TChallengePositionInfo = {
  challengeId: string;
  positionIdx: number;
  riskId: number;
  riskLimitValue: number;
  symbol: string;
  side: string;
  size: number;
  avgPrice: number;
  positionValue: number;
  autoAddMargin: boolean;
  positionStatus: string;
  leverage: number | null;
  breakEvenPrice: number | null;
  markPrice: number;
  liqPrice: number | null;
  positionIm: number | null;
  positionImByMp: number | null;
  positionMm: number | null;
  positionMmByMp: number | null;
  takeProfit: number | null;
  stopLoss: number | null;
  trailingStop: number | null;
  sessionAvgPrice: number | null;
  unrealisedPnl: number;
  curRealisedPnl: number;
  cumRealisedPnl: number;
  adlRankIndicator: number;
  createdTime: string;
  updatedTime: string;
  openTime: string;
  seq: number;
  isReduceOnly: boolean;
  mmrSysUpdatedTime: string | null;
  leverageSysUpdatedTime: string | null;
  updatedAt: string;
};
